spring:
  application:
    name: Administracion-Gestion-Inventario

  datasource:
    url: jdbc:mysql://localhost:3306/admin_gestion_today
    username: root
    password: mysql

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


project:
  poster: image/

base:
  url: "http://localhost:8080"